import './globals.css'
import { Inter } from 'next/font/google'
import Link from 'next/link'
import LoginBtn from '@/component/loginBtn'
import { getServerSession } from "next-auth"
import { authOptions } from '@/pages/api/auth/[...nextauth]'
// import { useState } from 'react' 안되 불가능
import { cookies } from 'next/dist/client/components/headers'
import DarkMode from './darkMode'


const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

//애네는 서버컴포넌트
export default async function RootLayout({ children }) {
  let session = await getServerSession(authOptions)
  console.log(session)

  //애네는 클라이언트 컴포넌트라서 여기서 사용못함... 
  // useState('darkMode')
  // localStorage.setItem('자료이름', '값')

  //서버컴포넌트에서 쓰려면 쿠키써야함
  let res = cookies().get('testCookie')
  console.log(res)


  return (
    <html lang="en">
      <body className={inter.className} >
        <div className="navbar">
          <Link href="/" className="logo">메인</Link>
          <Link href="/list">List</Link>
          <Link href="write">쓰기</Link>
          <LoginBtn session={session} />
          <DarkMode/>
        </div>
        {children}</body>
    </html>
  )
}
